#!/bin/bash
# 游戏项目初始化脚本
# 用法: ./setup.sh <项目名> [--template 模板] [--引擎 引擎]

set -e

PROJECT_NAME="${1:-MyGame}"
TEMPLATE="${3:-unity-2d}"
ENGINE="${4:-unity}"

echo "🎮 初始化游戏项目: $PROJECT_NAME"
echo "📋 模板: $TEMPLATE"
echo "🔧 引擎: $ENGINE"
echo ""

# 创建项目目录
mkdir -p "$PROJECT_NAME"
cd "$PROJECT_NAME"

# 初始化Git仓库
echo "📦 初始化 Git 仓库..."
git init

# 创建标准目录结构
echo "📁 创建项目结构..."
mkdir -p src/{scripts,scenes,prefabs,assets/{sprites,audio,materials}}
mkdir -p tests/{unit,integration}
mkdir -p docs/{design,api}
mkdir -p build/{dev,prod}
mkdir -p config

# 创建基础配置文件
echo "⚙️  创建配置文件..."
cat > config/project.json << EOF
{
  "name": "$PROJECT_NAME",
  "version": "0.1.0",
  "engine": "$ENGINE",
  "created": "$(date -Iseconds)",
  "features": []
}
EOF

# 创建README
cat > README.md << EOF
# $PROJECT_NAME

## 🎮 游戏简介

[TODO: 添加游戏简介]

## 🚀 快速开始

\`\`\`bash
# 安装依赖（如需要）
npm install

# 运行游戏
./run.sh
\`\`\`

## 📋 任务清单

- [ ] 核心游戏循环
- [ ] 玩家控制系统
- [ ] 敌人AI
- [ ] 音效系统
- [ ] UI界面

## 📄 文档

- [开发文档](docs/DEVELOPMENT.md)
- [测试文档](tests/README.md)
- [部署文档](docs/DEPLOYMENT.md)

---

*Created with OpenClaw Game Dev Workflow 🦞*
EOF

# 创建开发文档
cat > docs/DEVELOPMENT.md << EOF
# 开发文档

## 开发环境设置

### 安装要求
- Unity 2023.x LTS（如果使用Unity）
- Node.js 18+（如果需要脚本）
- Python 3.9+（如果需要工具）

### 开发流程

1. 使用 \`./dev-agent.sh \"任务描述\"\` 启动智能体
2. 智能体会自动生成代码
3. 代码生成后自动提交
4. 定期运行 \`./scripts/test-agent.sh\`

## 代码规范

- 使用驼峰命名法
- 每个类应有注释
- 提交信息格式: \`feat: 描述\`, \`fix: 描述\`, \`test: 描述\`

---

*Auto-generated by OpenClaw* 🦞
EOF

# 创建测试文档
cat > tests/README.md << EOF
# 测试文档

## 测试结构

- \`tests/unit/\` - 单元测试
- \`tests/integration/\` - 集成测试

## 运行测试

\`\`\`bash
# 运行所有测试
./scripts/test-agent.sh --all

# 运行单元测试
./scripts/test-agent.sh --unit

# 运行集成测试
./scripts/test-agent.sh --integration
\`\`\`

## 测试覆盖率目标

- 单元测试覆盖率 > 80%
- 所有核心功能必须有集成测试

---

*Auto-generated by OpenClaw* 🦞
EOF

# 安装GitHub Actions CI/CD
echo "🔄 配置 GitHub Actions..."
mkdir -p .github/workflows
cp ../templates/github-actions/workflow.yml .github/workflows/ci-cd.yml

# 创建.gitignore
cat > .gitignore << EOF
# Unity
[Ll]ibrary/
[Tt]emp/
[Oo]bj/
[Bb]uild/
[Bb]uilds/
[Ll]ogs/
[Mm]emory/
[Dd]ebugLog.txt

# Node
node_modules/
*.log

# Python
__pycache__/
*.pyc
.venv/

# OS
.DS_Store
Thumbs.db

# Build
build/*.unity
build/*.apk
EOF

# 初始提交
echo "📤 初始提交..."
git add .
git commit -m "chore: initialize game project with OpenClaw workflow 🦞"

echo ""
echo "✅ 项目初始化完成！"
echo ""
echo "📍 当前目录: $(pwd)"
echo ""
echo "🎯 下一步操作："
echo "   1. cd $PROJECT_NAME"
echo "   2. ./scripts/dev-agent.sh '开始开发游戏功能'"
echo "   3. ./scripts/test-agent.sh --all"
echo ""
echo "🦞 祝游戏开发顺利！"
